Salesforce CRM - APAC/IMEA/GTR_WP-22936_3/main/default/objects/Account/fields/Promotional_Budget__c.field-meta.xml
<CustomField>
    <fullName>Promotional_Budget__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Promotional Budget</label>
    <precision>16</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Promotional_Budget_Remaining__c.field-meta.xml
<CustomField>
    <fullName>Promotional_Budget_Remaining__c</fullName>
    <formula>Promotional_Budget__c - Promotional_Budget_Used__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Promotional Budget Remaining</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Salesforce CRM - APAC/IMEA/GTR_WP-22936_3/main/default/objects/Account/fields/Promotional_Budget_Used__c.field-meta.xml
<CustomField>
    <fullName>Promotional_Budget_Used__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Promotional Budget Used</label>
    <precision>16</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PMI_Actual__c/fields/Act_Qty__c.field-meta.xml
<CustomField>
    <fullName>Act_Qty__c</fullName>
    <label>Act Qty</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PMI_Actual__c/fields/Activity__c.field-meta.xml
<CustomField>
    <fullName>Activity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Activity</label>
    <referenceTo>Promotion_Activity__c</referenceTo>
    <relationshipLabel>PMI Actuals</relationshipLabel>
    <relationshipName>PMI_Actuals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PMI_Actual__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Submit</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Rebate Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PMI_Actual__c/fields/Promotion_Material_Item__c.field-meta.xml
<CustomField>
    <fullName>Promotion_Material_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promotion Material Item</label>
    <referenceTo>Promotion_Material_Item__c</referenceTo>
    <relationshipLabel>PMI Actuals</relationshipLabel>
    <relationshipName>PMI_Actuals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promotion_Activity__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Promotion_Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promotion_Activity__c/fields/Account_Promotional_Target_ROI__c.field-meta.xml
<CustomField>
    <fullName>Account_Promotional_Target_ROI__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Account Promotional Target ROI</label>
    <precision>9</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Promotion_Activity__c/fields/Begin_Date__c.field-meta.xml
<CustomField>
    <fullName>Begin_Date__c</fullName>
    <description>INFOWELDERS</description>
    <label>Begin Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Promotion_Activity__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promotion_Activity__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>INFOWELDERS</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Promotion_Activity__c/fields/Is_Length_in_Years__c.field-meta.xml
<CustomField>
    <fullName>Is_Length_in_Years__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Length in Years</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Promotion_Activity__c/fields/Length_of_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Length_of_Agreement__c</fullName>
    <description>Length of agreement in years</description>
    <label>Length of Agreement</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Promotion_Activity__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Infowelders</description>
    <label>Market</label>
    <referenceTo>Market__c</referenceTo>
    <relationshipName>Promotion_Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce CRM - APAC/IMEA/GTR_WP-22936_3/main/default/objects/Promotion_Activity__c/fields/Planned_Fee__c.field-meta.xml
<CustomField>
    <fullName>Planned_Fee__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Planned Fee</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

Salesforce CRM - APAC/IMEA/GTR_WP-22936_3/main/default/objects/Promotion_Activity__c/fields/PMI_Actual_Status__c.field-meta.xml
<CustomField>
    <fullName>PMI_Actual_Status__c</fullName>
    <label>PMI Actual Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Submit</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Reviewed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Promotion_Activity__c/fields/Requires_Special_Approval__c.field-meta.xml
<CustomField>
    <fullName>Requires_Special_Approval__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Requires Special Approval</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Promotion_Activity__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Preliminary</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Concept</fullName>
            </value>
            <value>
                <fullName>Presented</fullName>
            </value>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Updated</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Committed</fullName>
            </value>
            <value>
                <fullName>Signed</fullName>
            </value>
            <value>
                <fullName>PO Created</fullName>
            </value>
            <value>
                <fullName>Contact Complete</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce CRM - APAC/IMEA/GTR_WP-22936_3/main/default/objects/Promotion_Activity__c/fields/Total_PSA_Actual_ROI__c.field-meta.xml
<CustomField>
    <fullName>Total_PSA_Actual_ROI__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total PSA Actual ROI</label>
    <precision>9</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Promotion_Material_Item__c/fields/Activity__c.field-meta.xml
<CustomField>
    <fullName>Activity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Activity</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Activity is not active</errorMessage>
        <filterItems>
            <field>Promotion_Activity__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Promotion_Activity__c</referenceTo>
    <relationshipLabel>Promotion Material Items</relationshipLabel>
    <relationshipName>Promotion_Material_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promotion_Material_Item__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Submit</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Promotion_Material_Item__c/fields/Current_Volume_Bottles__c.field-meta.xml
<CustomField>
    <fullName>Current_Volume_Bottles__c</fullName>
    <formula>Current_Volume__c * Product_Pack_Qty__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Current Volume Bottles</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Promotion_Material_Item__c/fields/Plan_Rebate__c.field-meta.xml
<CustomField>
    <fullName>Plan_Rebate__c</fullName>
    <label>Plan Discount</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Promotion_Material_Item__c/fields/Plan_Volume__c.field-meta.xml
<CustomField>
    <fullName>Plan_Volume__c</fullName>
    <label>Plan Volume</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Promotion_Material_Item__c/fields/Product_Custom__c.field-meta.xml
<CustomField>
    <fullName>Product_Custom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>NPA Rollout: Used to store the related Product. /* API name need to be changed to Product__c after Product remediation*/</description>
    <label>Product Name</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Promotion Material Items</relationshipLabel>
    <relationshipName>Promotion_Material_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce CRM - APAC/IMEA/GTR_WP-22936_3/main/default/objects/Promotion_Material_Item__c/fields/Total_Fee_Paid__c.field-meta.xml
<CustomField>
    <fullName>Total_Fee_Paid__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Fee Paid</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/Korea_PSA_Contract_Controller.cls
/**
 * Test Class:   Korea_PSA_Contract_Controller_Test
 */
public with sharing class Korea_PSA_Contract_Controller {

    public Promotion_Activity__c thePSA;
    public List<Promotion_Material_Item__c> promotionMaterialItems 	{ get; set; }
    public List<PMI_Actual__c> actuals 								{ get; set; }

    public String specialApprovalReason 							{ get; set; }
    
    public void setThePSA(Promotion_Activity__c pa) {
        
        // This is your original Production query
        thePSA = [SELECT Id, Name, RecordTypeId, RecordType.Name, Status__c, Market__c, Account__c, Account__r.Name, Account_Owner__c, Account_Owner_Sales_Region__c,
                  		Account__r.Promotional_Budget__c, Account__r.Promotional_Budget_Used__c, Account__r.Promotional_Budget_Remaining__c, Account_Promotional_Target_ROI__c,
                  		CreatedById, CreatedBy.Name, OwnerId, Owner.Name, Begin_Date__c, End_Date__c, Is_Length_in_Years__c, Length_of_Agreement__c, 
                  		Contact__c, Contact__r.Name, Contact__r.MobilePhone, Contact__r.Email, Activity_Budget__c, Planned_Fee__c, Total_Fee_Paid__c,
                  		Total_PSA_ROI__c, Total_PSA_Actual_ROI__c, Requires_Special_Approval__c, PMI_Actual_Status__c,
                         (SELECT Id, Name, Product_Custom__c, Product_Name__c, Plan_Volume__c, Plan_Volume_Bottles__c, Current_Volume__c, Current_Volume_Bottles__c, Plan_Rebate__c 
                             FROM Promotion_Material_Items__r),
                  		(SELECT Id, Year__c, Month_Name_Abbrev__c, Product_Name__c, Act_Qty__c, Act_Qty_Bottles__c, Promotion_Material_Item__r.Plan_Volume__c, Promotion_Material_Item__r.Plan_Volume_Bottles__c,
                        		Promotion_Material_Item__r.Plan_Rebate__c, Payment_Date__c, Promotion_Material_Item__r.Current_Volume__c, Promotion_Material_Item__r.Current_Volume_Bottles__c,
                         		Approval_Status__c, Rebate_Type__c
                        	FROM PMI_Actuals__r)
                  FROM Promotion_Activity__c 
                  WHERE Id = :pa.Id];
        
        specialApprovalReason = '';
        if (thePSA.Requires_Special_Approval__c) {
            if (thePSA.Account__r.Promotional_Budget__c < thePSA.Total_Fee_Paid__c) {
                specialApprovalReason = Label.Budget_Overrun;
            }
            if (thePSA.Account_Promotional_Target_ROI__c < thePSA.Total_PSA_Actual_ROI__c || thePSA.Total_PSA_ROI__c < thePSA.Total_PSA_Actual_ROI__c) {
                specialApprovalReason += ' and ' + Label.ROI_Threshold_Risk;
            }
        }
        
        actuals = new List<PMI_Actual__c>();
        for(PMI_Actual__c pmia : thePSA.PMI_Actuals__r) {
            if (pmia.Approval_Status__c == 'Submit' && pmia.Rebate_Type__c == 'Volume') {
                actuals.add(pmia);
            }
        }
    }

    public Promotion_Activity__c getThePSA() {
        return thePSA;
    }
    
}