force-app/main/default/objects/PMI_Actual__c/fields/Act_Qty__c.field-meta.xml
<CustomField>
    <fullName>Act_Qty__c</fullName>
    <label>Act Qty</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PMI_Actual__c/fields/Activity__c.field-meta.xml
<CustomField>
    <fullName>Activity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Activity</label>
    <referenceTo>Promotion_Activity__c</referenceTo>
    <relationshipLabel>PMI Actuals</relationshipLabel>
    <relationshipName>PMI_Actuals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PMI_Actual__c/fields/Actual_Wholesaler__c.field-meta.xml
<CustomField>
    <fullName>Actual_Wholesaler__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Actual Wholesaler</label>
    <referenceTo>Wholesaler__c</referenceTo>
    <relationshipLabel>PMI Actuals</relationshipLabel>
    <relationshipName>PMI_Actuals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PMI_Actual__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Submit</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Rebate Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PMI_Actual__c/fields/External_Key__c.field-meta.xml
<CustomField>
    <fullName>External_Key__c</fullName>
    <description>= PromotionID + &#39;_&#39; + Product__c + &#39;_&#39; + MonthName</description>
    <externalId>true</externalId>
    <label>External Key</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PMI_Actual__c/fields/Period__c.field-meta.xml
<CustomField>
    <fullName>Period__c</fullName>
    <label>Period</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PMI_Actual__c/fields/Promotion__c.field-meta.xml
<CustomField>
    <fullName>Promotion__c</fullName>
    <label>Promotion</label>
    <referenceTo>Promotion__c</referenceTo>
    <relationshipLabel>PMI Actuals</relationshipLabel>
    <relationshipName>PMI_Actuals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PMI_Actual__c/fields/Promotion_Material_Item__c.field-meta.xml
<CustomField>
    <fullName>Promotion_Material_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promotion Material Item</label>
    <referenceTo>Promotion_Material_Item__c</referenceTo>
    <relationshipLabel>PMI Actuals</relationshipLabel>
    <relationshipName>PMI_Actuals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PMI_Actual__c/fields/Rebate_Amount__c.field-meta.xml
<CustomField>
    <fullName>Rebate_Amount__c</fullName>
    <label>Rebate Amount</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PMI_Actual__c/fields/Rebate_Type__c.field-meta.xml
<CustomField>
    <fullName>Rebate_Type__c</fullName>
    <label>Rebate Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Volume</fullName>
                <default>true</default>
                <label>Volume</label>
            </value>
            <value>
                <fullName>Listing Fee</fullName>
            </value>
            <value>
                <fullName>Promotional Activity</fullName>
            </value>
            <value>
                <fullName>Training &amp; Advocacy</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Free Goods</fullName>
            </value>
            <value>
                <fullName>Brand Support</fullName>
            </value>
            <value>
                <fullName>Discount</fullName>
            </value>
            <value>
                <fullName>Fee</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Promotion__c/fields/Promotion_Activity__c.field-meta.xml
<CustomField>
    <fullName>Promotion_Activity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Infowelders</description>
    <label>Promotion Activity</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 OR 2) AND 3</booleanFilter>
        <filterItems>
            <field>Promotion_Activity__c.Market__r.Name</field>
            <operation>equals</operation>
            <valueField>$User.Market__c</valueField>
        </filterItems>
        <filterItems>
            <field>$User.Market__c</field>
            <operation>equals</operation>
            <value>ALL</value>
        </filterItems>
        <filterItems>
            <field>Promotion_Activity__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>Displaying only Active Promotion Activities in your Market</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Promotion_Activity__c</referenceTo>
    <relationshipLabel>Promotions</relationshipLabel>
    <relationshipName>Promotions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promotion_Activity__c/fields/Wholesaler_Preferred__c.field-meta.xml
<CustomField>
    <fullName>Wholesaler_Preferred__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Wholesaler Preferred</label>
    <referenceTo>Wholesaler__c</referenceTo>
    <relationshipName>Activities_Wholesaler_Preferred</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promotion_Material_Item__c/fields/Activity__c.field-meta.xml
<CustomField>
    <fullName>Activity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Activity</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Activity is not active</errorMessage>
        <filterItems>
            <field>Promotion_Activity__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Promotion_Activity__c</referenceTo>
    <relationshipLabel>Promotion Material Items</relationshipLabel>
    <relationshipName>Promotion_Material_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promotion_Material_Item__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Submit</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Promotion_Material_Item__c/fields/Promotion__c.field-meta.xml
<CustomField>
    <fullName>Promotion__c</fullName>
    <description>Infowelders: Used by CRM.
		NPA Rollout: Used to refer to Promotion.</description>
    <label>Promotion</label>
    <referenceTo>Promotion__c</referenceTo>
    <relationshipLabel>Promotion Material Items</relationshipLabel>
    <relationshipName>Promotion_Material_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/BuildInitialActualsForPSA.cls
public with sharing class BuildInitialActualsForPSA {
    @InvocableMethod
    public static void buildInitialActuals(List<String> activityIds) {
        String rtUKPSA = '';
        
        Map<String, Schema.RecordTypeInfo> rtiList = PMI_Actual__c.SObjectType.getDescribe().getRecordTypeInfosByName();
        if (rtiList.containsKey('UK - PSA')) {
            rtUKPSA = rtiList.get('UK - PSA').getRecordTypeId();
        }

        List<PMI_Actual__c> existingActuals = [SELECT Id, External_Key__c FROM PMI_Actual__c WHERE Activity__c =:activityIds AND External_Key__c LIKE '%_0'];
        Set<String> externalKeys = new Set<String>();
        for(PMI_Actual__c pmia : existingActuals) {
            if (!externalKeys.contains(pmia.External_Key__c)) {
                externalKeys.add(pmia.External_Key__c);
            }
        }

        List<PMI_Actual__c> actuals = new List<PMI_Actual__c>();
        Set<String> s_PSAWithActuals = new Set<String>();
        List<Promotion_Material_Item__c> items = [SELECT Id, Activity__c, Promotion__c, Activity__r.Wholesaler_Preferred__c
                                                    FROM Promotion_Material_Item__c 
                                                   WHERE Activity__c =:activityIds];

        String externalKey = '';
        Boolean addedActuals = false;
        if (items != null && items.size() > 0) {
            for(Promotion_Material_Item__c pmi : items) {
                addedActuals = false;
                externalKey = pmi.Promotion__c + '_' + pmi.Id + '_Volume_0';
                if (!externalKeys.contains(externalKey)) {
                    actuals.add(createPMIActual(pmi, 'Volume', rtUKPSA));
                    addedActuals = true;
                }
                externalKey = pmi.Promotion__c + '_' + pmi.Id + '_Listing Fee_0';
                if (!externalKeys.contains(externalKey)) {
                    actuals.add(createPMIActual(pmi, 'Listing Fee', rtUKPSA));
                    addedActuals = true;
                }
                externalKey = pmi.Promotion__c + '_' + pmi.Id + '_Promotional Activity_0';
                if (!externalKeys.contains(externalKey)) {
                    actuals.add(createPMIActual(pmi, 'Promotional Activity', rtUKPSA));
                    addedActuals = true;
                }
                externalKey = pmi.Promotion__c + '_' + pmi.Id + '_Training & Advocacy_0';
                if (!externalKeys.contains(externalKey)) {
                    actuals.add(createPMIActual(pmi, 'Training & Advocacy', rtUKPSA));
                    addedActuals = true;
                }
    
                if (addedActuals) {
                    if (!s_PSAWithActuals.contains(pmi.Activity__c)) {
                        s_PSAWithActuals.add(pmi.Activity__c);
                    }    
                }
                
            }
        }

        if (actuals.size() > 0) {
            insert actuals;

            List<Promotion_Activity__c> l = [SELECT Id, Has_Actual_Totals__c FROM Promotion_Activity__c WHERE Id =: s_PSAWithActuals];
            for(Promotion_Activity__c pa : l) {
                pa.Has_Actual_Totals__c = true;
            }
            update l;
        }
    }

    static PMI_Actual__c createPMIActual(Promotion_Material_Item__c pmi, String rebateType, String recordTypeId) {
        PMI_Actual__c pmia = new PMI_Actual__c();
        pmia.RecordTypeId = recordTypeId;
        pmia.Activity__c = pmi.Activity__c;
        pmia.Promotion__c = pmi.Promotion__c;
        pmia.Promotion_Material_Item__c = pmi.Id;
        pmia.Actual_Wholesaler__c = pmi.Activity__r.Wholesaler_Preferred__c;
        pmia.Period__c = 0;
        pmia.Has_Totals__c = true;
        pmia.Approval_Status__c = 'Rebate Complete';
        pmia.External_Key__c = pmi.Promotion__c + '_' + pmi.Id + '_'+rebateType+'-0';
        pmia.Rebate_Type__c = rebateType;
        pmia.Rebate_Amount__c = 0;
        pmia.Act_Qty__c = 0;
        pmia.Payment_Date__c = Date.today();

        return pmia;
    }
}