force-app/main/default/objects/PMI_Actual__c/fields/Activity__c.field-meta.xml
<CustomField>
    <fullName>Activity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Activity</label>
    <referenceTo>Promotion_Activity__c</referenceTo>
    <relationshipLabel>PMI Actuals</relationshipLabel>
    <relationshipName>PMI_Actuals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PMI_Actual__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Submit</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Rebate Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce CRM - APAC/IMEA/GTR_WP-22936_3/main/default/objects/Promotion_Activity__c/fields/PMI_Actual_Status__c.field-meta.xml
<CustomField>
    <fullName>PMI_Actual_Status__c</fullName>
    <label>PMI Actual Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Submit</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Reviewed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Update_PSA_Actuals_Approvals.cls
public with sharing class Update_PSA_Actuals_Approvals {
    @InvocableMethod
    public static void Update_PSA_Actuals_Approvals(List<String> activityIds) {
        List<Promotion_Activity__c> activities = [SELECT Id, SalesProposal_Actuals_Updated__c, PMI_Actual_Status__c,
                                                    (SELECT Id, Approval_Status__c FROM PMI_Actuals__r WHERE Approval_Status__c = 'Submit')
                                                    FROM Promotion_Activity__c
                                                    WHERE Id =:activityIds];

        List<PMI_Actual__c> actualsToUpdate = new List<PMI_Actual__c>();
        for(Promotion_Activity__c theActivity : activities) {
            if (theActivity.PMI_Actuals__r != null && theActivity.PMI_Actuals__r.size() > 0) {
                for(PMI_Actual__c pmia : theActivity.PMI_Actuals__r) {
                    if (theActivity.PMI_Actual_Status__c == 'Approved' || theActivity.PMI_Actual_Status__c == 'Paid') {
                        pmia.Approval_Status__c = theActivity.PMI_Actual_Status__c;                        
                    } else {
                        pmia.Approval_Status__c = 'New';
                    }

                    actualsToUpdate.add(pmia);
                }

                theActivity.SalesProposal_Actuals_Updated__c = false;                
            }            
        }

        if (actualsToUpdate.size() > 0) {
            update actualsToUpdate;
            update activities;
        }
    }
}