force-app/main/default/objects/Promotion_Material_Item__c/fields/Activity__c.field-meta.xml
<CustomField>
    <fullName>Activity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Activity</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Activity is not active</errorMessage>
        <filterItems>
            <field>Promotion_Activity__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Promotion_Activity__c</referenceTo>
    <relationshipLabel>Promotion Material Items</relationshipLabel>
    <relationshipName>Promotion_Material_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promotion_Material_Item__c/fields/Drink_Strategy__c.field-meta.xml
<CustomField>
    <fullName>Drink_Strategy__c</fullName>
    <label>Drink Strategy</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Perfect Serve</fullName>
            </value>
            <value>
                <fullName>Menu - Outlet Creation</fullName>
            </value>
            <value>
                <fullName>Menu - First drink</fullName>
            </value>
            <value>
                <fullName>Menu - First in category</fullName>
            </value>
            <value>
                <fullName>Menu -American Whiskey section</fullName>
            </value>
            <value>
                <fullName>Online menu inclusion</fullName>
            </value>
            <value>
                <fullName>Online drink feature</fullName>
            </value>
            <value>
                <fullName>Jack Daniel&#39;s Christmas serve</fullName>
            </value>
            <value>
                <fullName>Jack &amp; Cola</fullName>
            </value>
            <value>
                <fullName>Jack Daniel&#39;s Apple Jack</fullName>
            </value>
            <value>
                <fullName>Jack Daniel&#39;s Godfather No.7</fullName>
            </value>
            <value>
                <fullName>Jack Daniel&#39;s Lynchburg Lemonade</fullName>
            </value>
            <value>
                <fullName>Jack Daniel&#39;s Old Fashioned</fullName>
            </value>
            <value>
                <fullName>Jack Daniel&#39;s Mr Jack Hard Shake</fullName>
            </value>
            <value>
                <fullName>Jack Daniel&#39;s Red Dog Smash</fullName>
            </value>
            <value>
                <fullName>Jack Daniel&#39;s Sour</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Promotion_Material_Item__c/fields/Outlet_to_Provide__c.field-meta.xml
<CustomField>
    <fullName>Outlet_to_Provide__c</fullName>
    <label>Outlet to Provide</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Social Media Posting</fullName>
            </value>
            <value>
                <fullName>Quarterly Sales Data</fullName>
            </value>
            <value>
                <fullName>Activity Sales Data</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Promotion_Material_Item__c/fields/Promotional_Activity__c.field-meta.xml
<CustomField>
    <fullName>Promotional_Activity__c</fullName>
    <label>Promotional Activity</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Point of Sale</fullName>
            </value>
            <value>
                <fullName>Sampling Activity</fullName>
            </value>
            <value>
                <fullName>Staff Incentive</fullName>
            </value>
            <value>
                <fullName>Timebound Activation</fullName>
            </value>
            <value>
                <fullName>Permanent Activation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Promotion_Material_Item__c/fields/Training_and_Advocacy__c.field-meta.xml
<CustomField>
    <fullName>Training_and_Advocacy__c</fullName>
    <label>Training and Advocacy</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Category Training</fullName>
            </value>
            <value>
                <fullName>Product Training</fullName>
            </value>
            <value>
                <fullName>Cocktail Training</fullName>
            </value>
            <value>
                <fullName>Bespoke Training</fullName>
            </value>
            <value>
                <fullName>Bespoke Advocacy Activation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mdapi_output/config/package_depletion.xml/classes/UK_PSA_CONTRACT_Controller.cls
public with sharing class UK_PSA_CONTRACT_Controller {
    public Promotion_Activity__c thePSA;
    public void setThePSA(Promotion_Activity__c pa) {
        thePSA = pa;
        List<Promotion_Material_Item__c> items = [SELECT Id, Name, Drink_Strategy__c, Promotional_Activity__c, Training_and_Advocacy__c, Outlet_to_Provide__c
                                                    FROM Promotion_Material_Item__c
                                                    WHERE Activity__c =:pa.Id];

/*
        if (items != null) {
            Set<String> setDrinkStrategy = new Set<String>();
            Set<String> setPromotionalActivity = new Set<String>();
            Set<String> setTrainingAndAdvocacy = new Set<String>();
            Set<String> setOutletToProvide = new Set<String>();

            List<String> l;
            for(Promotion_Material_Item__c pmi : items) {
                if (pmi.Drink_Strategy__c != null) {
                    l = pmi.Drink_Strategy__c.split(';');
                    setDrinkStrategy.addAll(l);
                }
                if (pmi.Promotional_Activity__c != null) {
                    l = pmi.Promotional_Activity__c.split(';');
                    setPromotionalActivity.addAll(l);
                }
                if (pmi.Training_and_Advocacy__c != null) {
                    l = pmi.Training_and_Advocacy__c.split(';');
                    setTrainingAndAdvocacy.addAll(l);
                }
                if (pmi.Outlet_to_Provide__c != null) {
                    l = pmi.Outlet_to_Provide__c.split(';');
                    setOutletToProvide.addAll(l);
                }
            }

            drinkStrategies = setDrinkStrategy.toString();
            drinkStrategies = drinkStrategies.removeStart('{');
            drinkStrategies = drinkStrategies.removeEnd('}');

            promotionalActivities = setPromotionalActivity.toString();
            promotionalActivities = promotionalActivities.removeStart('{');
            promotionalActivities = promotionalActivities.removeEnd('}');

            trainingAndAdvocacies = setTrainingAndAdvocacy.toString();
            trainingAndAdvocacies = trainingAndAdvocacies.removeStart('{');
            trainingAndAdvocacies = trainingAndAdvocacies.removeEnd('}');

            outletToProvideValues = setOutletToProvide.toString();
            outletToProvideValues = outletToProvideValues.removeStart('{');
            outletToProvideValues = outletToProvideValues.removeEnd('}');
        }
        */
    }
    public Promotion_Activity__c getThePSA() {
        return thePSA;
    }

    public String drinkStrategies { get; set; }
    
    public String promotionalActivities { get; set; }

    public String trainingAndAdvocacies { get; set; }

    public String outletToProvideValues { get; set; }


}