force-app/main/default/objects/Promotion_Material_Item__c/fields/Activity__c.field-meta.xml
<CustomField>
    <fullName>Activity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Activity</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Activity is not active</errorMessage>
        <filterItems>
            <field>Promotion_Activity__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Promotion_Activity__c</referenceTo>
    <relationshipLabel>Promotion Material Items</relationshipLabel>
    <relationshipName>Promotion_Material_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promotion_Material_Item__c/fields/Listing_Fee__c.field-meta.xml
<CustomField>
    <fullName>Listing_Fee__c</fullName>
    <label>Listing Fee</label>
    <precision>12</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Promotion_Material_Item__c/fields/Plan_Rebate__c.field-meta.xml
<CustomField>
    <fullName>Plan_Rebate__c</fullName>
    <label>Plan Discount</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Promotion_Material_Item__c/fields/Plan_Volume__c.field-meta.xml
<CustomField>
    <fullName>Plan_Volume__c</fullName>
    <label>Plan Volume</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Promotion_Material_Item__c/fields/Promotional_Activity_Value__c.field-meta.xml
<CustomField>
    <fullName>Promotional_Activity_Value__c</fullName>
    <label>Promotional Activity Value</label>
    <precision>12</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Promotion_Material_Item__c/fields/Training_and_Advocacy_Value__c.field-meta.xml
<CustomField>
    <fullName>Training_and_Advocacy_Value__c</fullName>
    <label>Training and Advocacy Value</label>
    <precision>12</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/UK_PSA_PushProposedValues.cls
public with sharing class UK_PSA_PushProposedValues {
    @InvocableMethod
    public static void pushProposedValues(List<String> activityIds) {
        List<Promotion_Material_Item__c> items = [SELECT Id, Name, Plan_Volume__c, Plan_Rebate__c, Listing_Fee__c, Promotional_Activity_Value__c,
                                                    Training_and_Advocacy_Value__c, Proposed_Plan_Volume__c, Proposed_Plan_Rebate__c, 
                                                    Proposed_Listing_Fee__c, Proposed_Promotional_Activity_Value__c, Proposed_Training_Advocacy_Value__c
                                                    FROM Promotion_Material_Item__c
                                                    WHERE Activity__c =: activityIds];

        List<Promotion_Material_Item__c> itemsToUpdate = new List<Promotion_Material_Item__c>();
        for(Promotion_Material_Item__c pmi : items) {
            if (pmi.Proposed_Plan_Volume__c != null && pmi.Plan_Volume__c != pmi.Proposed_Plan_Volume__c) {
                pmi.Plan_Volume__c = pmi.Proposed_Plan_Volume__c;
            }
            if (pmi.Proposed_Plan_Rebate__c != null && pmi.Plan_Rebate__c != pmi.Proposed_Plan_Rebate__c) {
                pmi.Plan_Rebate__c = pmi.Proposed_Plan_Rebate__c;
            }
            if (pmi.Proposed_Listing_Fee__c != null && pmi.Listing_Fee__c != pmi.Proposed_Listing_Fee__c) {
                pmi.Listing_Fee__c = pmi.Proposed_Listing_Fee__c;
            }
            if (pmi.Proposed_Promotional_Activity_Value__c != null && pmi.Promotional_Activity_Value__c != pmi.Proposed_Promotional_Activity_Value__c) {
                pmi.Promotional_Activity_Value__c = pmi.Proposed_Promotional_Activity_Value__c;
            }
            if (pmi.Proposed_Training_Advocacy_Value__c != null && pmi.Training_and_Advocacy_Value__c != pmi.Proposed_Training_Advocacy_Value__c) {
                pmi.Training_and_Advocacy_Value__c = pmi.Proposed_Training_Advocacy_Value__c;
            }
            itemsToUpdate.add(pmi);
        }
        if (itemsToUpdate.size() > 0) {
            update itemsToUpdate;
        }
    }
}