force-app/main/default/objects/Depletion__c/Depletion__c.object-meta.xml
<CustomObject>
    <label>Depletion</label>
    <nameField>
        <displayFormat>DEP-{YYYY}{000000}</displayFormat>
        <label>Depletion #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Depletions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Depletion__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Infowelders</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Depletions</relationshipLabel>
    <relationshipName>Depletions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Depletion__c/fields/Activity__c.field-meta.xml
<CustomField>
    <fullName>Activity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Activity</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The selected activity is not for this account</errorMessage>
        <filterItems>
            <field>$Source.Account__c</field>
            <operation>equals</operation>
            <valueField>Promotion_Activity__c.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Promotion_Activity__c</referenceTo>
    <relationshipLabel>Depletions</relationshipLabel>
    <relationshipName>Depletions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Depletion__c/fields/Activity_Name__c.field-meta.xml
<CustomField>
    <fullName>Activity_Name__c</fullName>
    <formula>Activity__r.Name</formula>
    <label>Activity Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Depletion__c/fields/Bottles__c.field-meta.xml
<CustomField>
    <fullName>Bottles__c</fullName>
    <description>Infowelders</description>
    <label>Bottles</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Depletion__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <formula>Custom_Product__r.Brand__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Brand</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Depletion__c/fields/Brand_US__c.field-meta.xml
<CustomField>
    <fullName>Brand_US__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brand (US)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Brand__c.eClips_Relevent__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Brand__c</referenceTo>
    <relationshipLabel>Depletions</relationshipLabel>
    <relationshipName>Depletions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Depletion__c/fields/Custom_Product__c.field-meta.xml
<CustomField>
    <fullName>Custom_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is created for Product Remediation process</description>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Depletions</relationshipLabel>
    <relationshipName>Depletions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Depletion__c/fields/Month_Text__c.field-meta.xml
<CustomField>
    <fullName>Month_Text__c</fullName>
    <label>Month</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Depletion__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Infowelders</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Depletions</relationshipLabel>
    <relationshipName>Depletions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Depletion__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <formula>Custom_Product__r.Name</formula>
    <label>Product Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Depletion__c/fields/Volume9L__c.field-meta.xml
<CustomField>
    <fullName>Volume9L__c</fullName>
    <label>Volume (9L)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Depletion__c/fields/Wholesaler__c.field-meta.xml
<CustomField>
    <fullName>Wholesaler__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Wholesaler</label>
    <referenceTo>Wholesaler__c</referenceTo>
    <relationshipLabel>Depletions</relationshipLabel>
    <relationshipName>Depletions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Depletion__c/fields/Wholesaler_Name__c.field-meta.xml
<CustomField>
    <fullName>Wholesaler_Name__c</fullName>
    <formula>Wholesaler__r.Name</formula>
    <label>Wholesaler Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Infowelders, NPA Rollout: Used to store the related Brand</description>
    <label>Brand</label>
    <referenceTo>Brand__c</referenceTo>
    <relationshipName>Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promotion__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Infowelders</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Promotions</relationshipLabel>
    <relationshipName>Promotions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Promotion__c/fields/Promotion_Activity__c.field-meta.xml
<CustomField>
    <fullName>Promotion_Activity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Infowelders</description>
    <label>Promotion Activity</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 OR 2) AND 3</booleanFilter>
        <filterItems>
            <field>Promotion_Activity__c.Market__r.Name</field>
            <operation>equals</operation>
            <valueField>$User.Market__c</valueField>
        </filterItems>
        <filterItems>
            <field>$User.Market__c</field>
            <operation>equals</operation>
            <value>ALL</value>
        </filterItems>
        <filterItems>
            <field>Promotion_Activity__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>Displaying only Active Promotion Activities in your Market</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Promotion_Activity__c</referenceTo>
    <relationshipLabel>Promotions</relationshipLabel>
    <relationshipName>Promotions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promotion_Activity__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Promotion_Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promotion_Activity__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>INFOWELDERS</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Promotion_Activity__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Infowelders</description>
    <label>Market</label>
    <referenceTo>Market__c</referenceTo>
    <relationshipName>Promotion_Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promotion_Activity__c/fields/Wholesaler_Alternate__c.field-meta.xml
<CustomField>
    <fullName>Wholesaler_Alternate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Wholesaler Alternate</label>
    <referenceTo>Wholesaler__c</referenceTo>
    <relationshipName>Activities_Wholesaler_Alternate</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promotion_Activity__c/fields/Wholesaler_Alternate_Name__c.field-meta.xml
<CustomField>
    <fullName>Wholesaler_Alternate_Name__c</fullName>
    <label>Wholesaler Alternate Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Promotion_Activity__c/fields/Wholesaler_Preferred__c.field-meta.xml
<CustomField>
    <fullName>Wholesaler_Preferred__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Wholesaler Preferred</label>
    <referenceTo>Wholesaler__c</referenceTo>
    <relationshipName>Activities_Wholesaler_Preferred</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promotion_Activity__c/fields/Wholesaler_Preferred_Name__c.field-meta.xml
<CustomField>
    <fullName>Wholesaler_Preferred_Name__c</fullName>
    <label>Wholesaler Preferred Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Promotion_Material_Item__c/fields/Activity__c.field-meta.xml
<CustomField>
    <fullName>Activity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Activity</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Activity is not active</errorMessage>
        <filterItems>
            <field>Promotion_Activity__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Promotion_Activity__c</referenceTo>
    <relationshipLabel>Promotion Material Items</relationshipLabel>
    <relationshipName>Promotion_Material_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promotion_Material_Item__c/fields/Product_Custom__c.field-meta.xml
<CustomField>
    <fullName>Product_Custom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>NPA Rollout: Used to store the related Product. /* API name need to be changed to Product__c after Product remediation*/</description>
    <label>Product Name</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Promotion Material Items</relationshipLabel>
    <relationshipName>Promotion_Material_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promotion_Material_Item__c/fields/Promotion__c.field-meta.xml
<CustomField>
    <fullName>Promotion__c</fullName>
    <description>Infowelders: Used by CRM.
		NPA Rollout: Used to refer to Promotion.</description>
    <label>Promotion</label>
    <referenceTo>Promotion__c</referenceTo>
    <relationshipLabel>Promotion Material Items</relationshipLabel>
    <relationshipName>Promotion_Material_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Depletions_Controller.cls
public with sharing class Depletions_Controller {
    /*
    public class depletionWrapper {
        @AuraEnabled 
        public String id { get; set }
        
        @AuraEnabled 
        public String recordTypeId { get; set; }

        @AuraEnabled 
        public String accountId { get; set; }

        @AuraEnabled 
        public String activityId { get; set; }

        @AuraEnabled 
        public String wholesalerId { get; set; }

        @AuraEnabled 
        public String month { get; set; }

        @AuraEnabled 
        public decimal bottles { get; set; }

        @AuraEnabled 
        public decimal volume { get; set; }

        public depletionWrapper() {
            id = '';
            recordTypeId = '';
            accountId = '';
            activityId = '';
            wholesalerId = '';
            month = '';
            bottles = 0;
            volume = 0;
        }
    }
    */
    private static String getUserMarket() {
        String marketName = 'Australia';
        User u = [SELECT Id, Name, Market__c FROM User WHERE Id =:UserInfo.getUserId()];
        if (String.isNotEmpty(u.Market__c)) {
            marketName = u.Market__c;
        }

        Market__c m = [SELECT Id, Name FROM Market__c WHERE Name =:marketName LIMIT 1];
        String marketId = '';
        if (m != null) {
            marketId = m.Id;
        }

        return marketId;
    }

    @AuraEnabled(cacheable=true)
    public static List<Depletion__c> getDepletions(String accountId){
        system.debug('accountId: ' + accountId);
        return [SELECT Id, Custom_Product__c, RecordTypeId, RecordType.Name, Product_Name__c, Activity__c, Activity_Name__c, Bottles__c,
                        Month_Text__c, Volume9L__c, Wholesaler__c, Wholesaler_Name__c
                FROM Depletion__c 
                WHERE Account__c =:accountId];
    }

    @AuraEnabled(cacheable=true) 
    public static Account getAccount(String accountId) {
        if (String.isEmpty(accountId)) {
            throw new AuraHandledException('Account Id is blank.');
        }

        return [SELECT Id, Name, Market__c, Market__r.Capture_Volume_in_Bottles__c,
                        (SELECT Id, Promotion_Activity__c, Promotion_Activity__r.Name, Promotion_Activity__r.Wholesaler_Preferred__c, Promotion_Activity__r.Wholesaler_Preferred_Name__c,
                                Promotion_Activity__r.Wholesaler_Alternate__c, Promotion_Activity__r.Wholesaler_Alternate_Name__c
                           FROM Promotions__r 
                          WHERE Promotion_Activity__r.End_Date__c > TODAY),
                        (SELECT Id, Custom_Product__c, RecordTypeId, RecordType.Name, Product_Name__c, Activity__c, Activity_Name__c, Bottles__c,
                                Month_Text__c, Volume9L__c, Wholesaler__c, Wholesaler_Name__c
                           FROM Depletions__r)
                  FROM Account 
                 WHERE Id =:accountId];
    }

    @AuraEnabled 
    public static List<Product__c> getProducts(String accountId) {
        System.debug('accountId: ' + accountId);
        String marketId = '';
        if (String.isEmpty(accountId)) {
            marketId = getUserMarket();
        } else {
            Account a = [SELECT Id, Name, Market__c FROM Account WHERE Id =:accountId];
            if (a != null) {
                marketId = a.Market__c;
            } else {
                marketId = getUserMarket();
            }
        }

        return [SELECT Id, Name, Brand__c, Brand_Name__c, Consolidated_Name__c, Pack_Quantity__c, Unit_Size__c,
                        (SELECT Id, Name, Activity__c, Activity_Name__c FROM Promotion_Material_Items__r WHERE Activity__r.End_Date__c > TODAY) 
                  FROM Product__c 
                 WHERE IsActive__c = true
                   AND Market__c =:marketId
                   AND RecordType.DeveloperName = 'Wet_Goods'
                   AND (Channel__c = 'On' OR Channel__c = 'Both')
                   AND Supplier__c = 'B-F'
                ORDER BY Sort_Order__c];
    }
    
}