force-app/main/default/objects/Promotion_Activity__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Promotion_Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promotion_Activity__c/fields/Begin_Date__c.field-meta.xml
<CustomField>
    <fullName>Begin_Date__c</fullName>
    <description>INFOWELDERS</description>
    <label>Begin Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Promotion_Activity__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promotion_Activity__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>INFOWELDERS</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Promotion_Activity__c/fields/Is_Length_in_Years__c.field-meta.xml
<CustomField>
    <fullName>Is_Length_in_Years__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Length in Years</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Promotion_Activity__c/fields/Length_of_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Length_of_Agreement__c</fullName>
    <description>Length of agreement in years</description>
    <label>Length of Agreement</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Promotion_Activity__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Infowelders</description>
    <label>Market</label>
    <referenceTo>Market__c</referenceTo>
    <relationshipName>Promotion_Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promotion_Activity__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Preliminary</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Concept</fullName>
            </value>
            <value>
                <fullName>Presented</fullName>
            </value>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Updated</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Committed</fullName>
            </value>
            <value>
                <fullName>Signed</fullName>
            </value>
            <value>
                <fullName>PO Created</fullName>
            </value>
            <value>
                <fullName>Contact Complete</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Promotion_Activity__c/fields/Total_Listing_Fee__c.field-meta.xml
<CustomField>
    <fullName>Total_Listing_Fee__c</fullName>
    <label>Total Listing Fee</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Promotion_Material_Item__c/fields/Activity__c.field-meta.xml
<CustomField>
    <fullName>Activity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Activity</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Activity is not active</errorMessage>
        <filterItems>
            <field>Promotion_Activity__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Promotion_Activity__c</referenceTo>
    <relationshipLabel>Promotion Material Items</relationshipLabel>
    <relationshipName>Promotion_Material_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promotion_Material_Item__c/fields/Plan_Volume__c.field-meta.xml
<CustomField>
    <fullName>Plan_Volume__c</fullName>
    <label>Plan Volume</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Promotion_Material_Item__c/fields/Product_Custom__c.field-meta.xml
<CustomField>
    <fullName>Product_Custom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>NPA Rollout: Used to store the related Product. /* API name need to be changed to Product__c after Product remediation*/</description>
    <label>Product Name</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Promotion Material Items</relationshipLabel>
    <relationshipName>Promotion_Material_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Brazil_PSA_Contract_Controller.cls
public with sharing class Brazil_PSA_Contract_Controller {
    public Promotion_Activity__c thePSA;
    public void setThePSA(Promotion_Activity__c pa) {
        thePSA = [SELECT Id, Name, RecordTypeId, RecordType.Name, Status__c, Market__c, Market_Filter__c, Account__c, Account__r.Name, Account__r.English_Name__c,
                         Total_Listing_Fee__c, Account__r.ShippingStreet, Account__r.ILN_Code__c, Account__r.Tax_Number_PL__c,
                         Number_of_Payments__c, Begin_Date__c, End_Date__c, Is_Length_in_Years__c, Length_of_Agreement__c,
                         CreatedById, CreatedBy.Name, CreatedBy.MobilePhone, CreatedBy.Email, Contact__c, Contact__r.Name, Contact__r.MobilePhone, Contact__r.Email,
                  		 Activity_Budget__c, Account__r.Owner.Name, Account__r.Owner.Manager.Name, Account__r.ShippingPostalCode,
                  	(SELECT Id, Name, Product__c, Product_Name__c, Plan_Volume__c, Plan_Volume_Bottles__c
                       FROM Promotion_Material_Items__r)
           		    FROM Promotion_Activity__c 
		            WHERE Id =:pa.Id];

        ownerName = thePSA.Account__r.Owner.Name;
        ownerManagerName = thePSA.Account__r.Owner.Manager.Name;
        numberOfPayments = Integer.valueOf(thePSA.Number_of_Payments__c);
        totalBudget = thePSA.Activity_Budget__c;
        promotionMaterialItems = thePSA.Promotion_Material_Items__r;
        formattedTotalBudget = NumberToWords.english_number(thePSA.Activity_Budget__c);
        System.debug('formatted total listing fee: ' + formattedTotalBudget);

        firstPaymentAmount = thePSA.Activity_Budget__c;
        secondPaymentAmount = 0;
        thirdPaymentAmount = 0;
        fourthPaymentAmount = 0;
        if (numberOfPayments == 2) {
            firstPaymentAmount = thePSA.Activity_Budget__c * 0.6;
            secondPaymentAmount = thePSA.Activity_Budget__c - firstPaymentAmount;
        } else if (numberOfPayments == 3) {
            firstPaymentAmount = thePSA.Activity_Budget__c * 0.5;
            secondPaymentAmount = (thePSA.Activity_Budget__c - firstPaymentAmount) * 0.3;
            thirdPaymentAmount = thePSA.Activity_Budget__c - firstPaymentAmount - secondPaymentAmount;
        } else if (numberOfPayments == 4) {
            firstPaymentAmount = thePSA.Activity_Budget__c * 0.4;
            secondPaymentAmount = (thePSA.Activity_Budget__c - firstPaymentAmount) * 0.4;
            thirdPaymentAmount = (thePSA.Activity_Budget__c - firstPaymentAmount - secondPaymentAmount) * 0.2;
            fourthPaymentAmount = thePSA.Activity_Budget__c - firstPaymentAmount - secondPaymentAmount - thirdPaymentAmount;
        }

        formattedFirstPaymentAmount = NumberToWords.english_number(firstPaymentAmount);
        formattedSecondPaymentAmount = NumberToWords.english_number(secondPaymentAmount);
        formattedThirdPaymentAmount = NumberToWords.english_number(thirdPaymentAmount);
        formattedFourthPaymentAmount = NumberToWords.english_number(fourthPaymentAmount);

        formattedLengthOfAgreement = NumberToWords.english_number(thePSA.Length_of_Agreement__c);

        ApprovalHistory history = new ApprovalHistory();
        DateTime completedDate;

        List<ProcessInstance> piList = [SELECT Id, CreatedDate, TargetObjectid, Status, ElapsedTimeInDays, ElapsedTimeInHours, ElapsedTimeInMinutes, 
                                            (SELECT Id, CreatedDate, StepStatus, Comments, Actor.Name, Actor.UserRole.Name, ElapsedTimeInDays, ElapsedTimeInHours, 
                                                    ElapsedTimeInMinutes, IsPending 
                                                FROM StepsAndWorkItems 
                                            ORDER BY ProcessNodeId) 
                                        FROM ProcessInstance 
                                        WHERE TargetObjectId =:thePSA.Id 
                                    ORDER BY CreatedDate];      
        if (piList != null && piList.size() > 0) {
            history.CreatedDate = piList.get(0).CreatedDate.format('EE, dd MMM YYYY, h:mm a');
            for (ProcessInstance pi : piList) {
                if (pi.StepsAndWorkItems != null) {
                    System.debug('# of work items: ' + pi.StepsAndWorkItems.size());
                }
                if (pi.StepsAndWorkItems != null && pi.StepsAndWorkItems.size() > 0) {                        
                    for(Integer i = 0; i < pi.StepsAndWorkitems.size(); i++) {
                        System.debug('actor: ' + pi.StepsAndWorkItems[i].Actor.Name + ', status: ' + pi.StepsAndWorkItems[i].StepStatus);

                        completedDate = pi.CreatedDate;
                        if (pi.StepsAndWorkItems[i].ElapsedTimeInMinutes != null) {
                            completedDate = pi.CreatedDate.addMinutes((Integer)pi.StepsAndWorkItems[i].ElapsedTimeInMinutes);
                        }

                        history.items.add(new ApprovalHistoryItem(pi.StepsAndWorkItems[i].Actor.Name, pi.StepsAndWorkItems[i].StepStatus, pi.StepsAndWorkItems[i].Comments, completedDate, pi.StepsAndWorkItems[i].Actor.UserRole.Name));
                    }                    
                }
            }
        }        

        psaApprovalHistory = history;
    }
    public Promotion_Activity__c getThePSA() {
        return thePSA;
    }

    public List<Promotion_Material_Item__c> promotionMaterialItems { get; set; }
    public String ownerName { get; set; }
    public String ownerManagerName { get; set; }
    public Decimal totalBudget { get; set; }
    public String formattedTotalBudget { get; set; }
    public Decimal totalPlanVolume { get; set; }
    public Integer numberOfPayments { get; set; }
    public Decimal firstPaymentAmount { get; set; }
    public String formattedFirstPaymentAmount { get; set; }
    public Decimal secondPaymentAmount { get; set; }
    public String formattedSecondPaymentAmount { get; set; }
    public Decimal thirdPaymentAmount { get; set; }
    public String formattedThirdPaymentAmount { get; set; }
    public Decimal fourthPaymentAmount { get; set; }
    public String formattedFourthPaymentAmount { get; set; }
    public String formattedLengthOfAgreement { get; set; }
    public ApprovalHistory psaApprovalHistory { get; set; }
    
}