force-app/main/default/objects/Promotion_Activity__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Promotion_Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promotion_Activity__c/fields/Activity_Type__c.field-meta.xml
<CustomField>
    <fullName>Activity_Type__c</fullName>
    <label>Activity Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>HZ national</fullName>
            </value>
            <value>
                <fullName>HZ regional</fullName>
            </value>
            <value>
                <fullName>B2B Werbung</fullName>
            </value>
            <value>
                <fullName>Vorverkauf</fullName>
            </value>
            <value>
                <fullName>Mengenabfrage</fullName>
            </value>
            <value>
                <fullName>Zuteilung</fullName>
            </value>
            <value>
                <fullName>Talon</fullName>
            </value>
            <value>
                <fullName>Messe</fullName>
            </value>
            <value>
                <fullName>Aktionsgondel</fullName>
            </value>
            <value>
                <fullName>Aktionspreis</fullName>
            </value>
            <value>
                <fullName>Pakiet zakupowy LCH 7%</fullName>
            </value>
            <value>
                <fullName>Pakiet zakupowy WH</fullName>
            </value>
            <value>
                <fullName>Gazetka LCH</fullName>
            </value>
            <value>
                <fullName>Gazetka HURT</fullName>
            </value>
            <value>
                <fullName>Gazetka PODHURT</fullName>
            </value>
            <value>
                <fullName>Gezetka DETAL</fullName>
            </value>
            <value>
                <fullName>Stand Detal</fullName>
            </value>
            <value>
                <fullName>Stand Pernamentny</fullName>
                <label>Stand Pernamentny LECLERC</label>
            </value>
            <value>
                <fullName>Ekspozycja Platformowa</fullName>
                <label>Ekspozycja Platformowa LECLERC</label>
            </value>
            <value>
                <fullName>Rewitalizacja</fullName>
            </value>
            <value>
                <fullName>Mastershelf</fullName>
            </value>
            <value>
                <fullName>Pakiet odsprzedażowy</fullName>
            </value>
            <value>
                <fullName>Gazetki Sieci Franczyzowe</fullName>
            </value>
            <value>
                <fullName>Wsparcie Sprzedaży Sieci Franczyzowe</fullName>
            </value>
            <value>
                <fullName>Direct Rebate</fullName>
            </value>
            <value>
                <fullName>Coupon</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Promotion_Activity__c/fields/All_Child_Accounts_Included__c.field-meta.xml
<CustomField>
    <fullName>All_Child_Accounts_Included__c</fullName>
    <defaultValue>false</defaultValue>
    <label>All Child Accounts Included</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Promotion_Activity__c/fields/Begin_Date__c.field-meta.xml
<CustomField>
    <fullName>Begin_Date__c</fullName>
    <description>INFOWELDERS</description>
    <label>Begin Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Promotion_Activity__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promotion_Activity__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>INFOWELDERS</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Promotion_Activity__c/fields/Is_Length_in_Years__c.field-meta.xml
<CustomField>
    <fullName>Is_Length_in_Years__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Length in Years</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Promotion_Activity__c/fields/Length_of_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Length_of_Agreement__c</fullName>
    <description>Length of agreement in years</description>
    <label>Length of Agreement</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Promotion_Activity__c/fields/Limit_to_Selected_Accounts__c.field-meta.xml
<CustomField>
    <fullName>Limit_to_Selected_Accounts__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Enable this option not auto add any new child accounts that might be created after the Activity (PSA) has been created.</description>
    <label>Limit to Selected Accounts</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Promotion_Activity__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Infowelders</description>
    <label>Market</label>
    <referenceTo>Market__c</referenceTo>
    <relationshipName>Promotion_Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promotion_Activity__c/fields/Percentage_Visibility__c.field-meta.xml
<CustomField>
    <fullName>Percentage_Visibility__c</fullName>
    <label>Percentage Visibility</label>
    <precision>4</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Promotion_Activity__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Preliminary</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Concept</fullName>
            </value>
            <value>
                <fullName>Presented</fullName>
            </value>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Updated</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Committed</fullName>
            </value>
            <value>
                <fullName>Signed</fullName>
            </value>
            <value>
                <fullName>PO Created</fullName>
            </value>
            <value>
                <fullName>Contact Complete</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Promotion_Activity__c/fields/Wholesaler_Alternate__c.field-meta.xml
<CustomField>
    <fullName>Wholesaler_Alternate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Wholesaler Alternate</label>
    <referenceTo>Wholesaler__c</referenceTo>
    <relationshipName>Activities_Wholesaler_Alternate</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promotion_Activity__c/fields/Wholesaler_Alternate_Name__c.field-meta.xml
<CustomField>
    <fullName>Wholesaler_Alternate_Name__c</fullName>
    <label>Wholesaler Alternate Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Promotion_Activity__c/fields/Wholesaler_Preferred__c.field-meta.xml
<CustomField>
    <fullName>Wholesaler_Preferred__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Wholesaler Preferred</label>
    <referenceTo>Wholesaler__c</referenceTo>
    <relationshipName>Activities_Wholesaler_Preferred</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promotion_Activity__c/fields/Wholesaler_Preferred_Name__c.field-meta.xml
<CustomField>
    <fullName>Wholesaler_Preferred_Name__c</fullName>
    <label>Wholesaler Preferred Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PSAWrapper.cls
/**
 * Test Class:  PromotionalSalesAgreementController_Test
 */
public with sharing class PSAWrapper {
    public class PSAItemWrapper {
        @AuraEnabled 
        public String id  { get; set; }
        @AuraEnabled 
        public String productId     { get; set; }
        
        @AuraEnabled
        public Integer volumeForecast  { get; set; }

        @AuraEnabled 
        public Decimal discount { get; set; }

        @AuraEnabled 
        public Decimal discountPercent { get; set; }

        @AuraEnabled 
        public String brandStatus { get; set; }

        @AuraEnabled 
        public Decimal listingFee { get; set; }

        @AuraEnabled 
        public String drinkStrategy { get; set; }

        @AuraEnabled 
        public String promotionalActivity { get; set; }

        @AuraEnabled 
        public Decimal promotionalActivityAmount { get; set; }

        @AuraEnabled 
        public String trainingAndAdvocacy { get; set; }

        @AuraEnabled 
        public Decimal trainingAndAdvocacyAmount { get; set; }

        @AuraEnabled 
        public Decimal brandSupport { get; set; }

        @AuraEnabled 
        public String outletToProvide { get; set; }

        @AuraEnabled 
        public Decimal freeBottleQty { get; set; }

        @AuraEnabled 
        public Date freeGoodsGivenDate { get; set; }

        @AuraEnabled 
        public String freeGoodsReason { get; set; }

        @AuraEnabled 
        public String brandVisibility { get; set; }

        @AuraEnabled 
        public String productVisibility { get; set; }

        @AuraEnabled 
        public Decimal planRebateLiability { get; set; }

        @AuraEnabled 
        public Decimal planRebateVolume { get; set; }

    }

    public class PSAAccountWrapper {
        @AuraEnabled
        public Account account { get; set; }
        
        @AuraEnabled
        public Boolean isSelected { get; set; }
    }

    @AuraEnabled 
    public String id    { get; set; }

    @AuraEnabled 
    public String recordTypeId  { get; set; }

    @AuraEnabled 
    public String recordTypeName  { get; set; }

    @AuraEnabled 
    public String marketId  { get; set; }

    @AuraEnabled 
    public String marketName { get; set; }

    @AuraEnabled 
    public String parentAccountId { get; set; }

    @AuraEnabled 
    public Boolean allChildAccountsIncluded { get; set; }

    @AuraEnabled 
    public String signingCustomerId { get; set; }

    @AuraEnabled 
    public String signingCustomerName { get; set; }

    @AuraEnabled 
    public String signingCustomerFirstName { get; set; }

    @AuraEnabled 
    public String signingCustomerLastName { get; set; }

    @AuraEnabled
    public String signingCustomerEmail { get; set; }

    @AuraEnabled 
    public Integer lengthOfPSA { get; set; }

    @AuraEnabled
    public Boolean isLengthInYears { get; set; }

    @AuraEnabled 
    public Date beginDate { get; set; }

    @AuraEnabled 
    public Date endDate { get; set; }

    @AuraEnabled 
    public String wholesalerPreferredId { get; set; }

    @AuraEnabled 
    public String wholesalerPreferredName { get; set; }

    @AuraEnabled 
    public String wholesalerAlternateId { get; set; }

    @AuraEnabled 
    public String wholesalerAlternateName { get; set; }

    @AuraEnabled 
    public String accountWholesalerPreferred { get; set; }

    @AuraEnabled 
    public String accountWholesalerPreferredName { get; set; }

    @AuraEnabled 
    public String accountWholesalerAlternate { get; set; }

    @AuraEnabled 
    public String accountWholesalerAlternateName { get; set; }

    @AuraEnabled 
    public String status { get; set; }

    @AuraEnabled 
    public String promotionType { get; set; }

    @AuraEnabled 
    public String comments { get; set; }

    @AuraEnabled 
    public String message { get; set; }

    @AuraEnabled 
    public String purchaseOrder { get; set; }

    @AuraEnabled 
    public Boolean mpoPrestige { get; set; }

    @AuraEnabled 
    public Boolean limitToSelectedAccounts { get; set; }

    @AuraEnabled 
    public Integer numberOfPayments { get; set; }

    @AuraEnabled
    public String paymentConfigurations { get; set; }

    @AuraEnabled 
    public Decimal totalBudget { get; set; }

    @AuraEnabled 
    public Decimal percentageVisibility { get; set; }

    @AuraEnabled 
    public Boolean isDirectRebate { get; set; }

    @AuraEnabled 
    public List<SelectableItem> accounts { get; set; }

    @AuraEnabled 
    public List<String> accountsToDelete { get; set; }

    @AuraEnabled 
    public List<PSAItemWrapper> items { get; set; }

    @AuraEnabled 
    public List<String> itemsToDelete { get; set; }

    public PSAWrapper() {
        this.id = '';
        this.recordTypeId = '';
        this.recordTypeName = '';
        this.marketId = '';
        this.marketName = '';
        this.parentAccountId = '';
        this.allChildAccountsIncluded = false;
        this.signingCustomerId = '';
        this.signingCustomerName = '';
        this.signingCustomerFirstName = '';
        this.signingCustomerLastName = '';
        this.signingCustomerEmail = '';
        this.lengthOfPSA = 0;
        this.isLengthInYears = true;
        this.beginDate = null;
        this.endDate = null;
        this.accountWholesalerPreferred = '';
        this.accountWholesalerPreferredName = '';
        this.accountWholesalerAlternate = '';
        this.accountWholesalerAlternateName = '';
        this.wholesalerAlternateId = '';
        this.wholesalerAlternateName = '';
        this.wholesalerPreferredId = '';
        this.wholesalerAlternateName = '';
        this.status = 'OK';
        this.promotionType = '';
        this.message = '';
        this.purchaseOrder = '';
        this.comments = '';
        this.mpoPrestige = false;
        this.limitToSelectedAccounts = true;
        this.numberOfPayments = 1;
        this.paymentConfigurations = '';
        this.totalBudget = 0;
        this.percentageVisibility = 0;
        this.isDirectRebate = true;

        this.accounts = new List<SelectableItem>();
        this.accountsToDelete = new List<String>();
        this.items = new List<PSAItemWrapper>();
        this.itemsToDelete = new List<String>();
    }

    public PSAWrapper(Promotion_Activity__c psa) {
        this.id = psa.Id;
        this.recordTypeId = psa.RecordTypeId;
        this.recordTypeName = psa.RecordType.Name;
        this.marketId = psa.Market__c;
        this.marketName = psa.Market__r.Name;
        this.parentAccountId = psa.Account__c;
        this.allChildAccountsIncluded = psa.All_Child_Accounts_Included__c;
        this.signingCustomerId = psa.Contact__c;
        if (psa.Contact__r != null) {
            this.signingCustomerFirstName = psa.Contact__r.FirstName;
            this.signingCustomerLastName = psa.Contact__r.LastName;
            this.signingCustomerName = psa.Contact__r.Name;
            this.signingCustomerEmail = psa.Contact__r.Email;    
        }
        this.lengthOfPSA = Integer.valueOf(psa.Length_of_Agreement__c);
        this.isLengthInYears = psa.Is_Length_in_Years__c;
        this.mpoPrestige = psa.MPO_Prestige__c;
        this.beginDate = psa.Begin_Date__c;
        this.endDate = psa.End_Date__c;
        this.wholesalerAlternateId = psa.Wholesaler_Alternate__c;
        this.wholesalerAlternateName = psa.Wholesaler_Alternate_Name__c;
        this.wholesalerPreferredId = psa.Wholesaler_Preferred__c;
        this.wholesalerPreferredName = psa.Wholesaler_Preferred_Name__c;
        this.status = psa.Status__c;
        this.promotionType = psa.Promotion_Type__c;
        this.purchaseOrder = psa.Purchase_Order__c;
        this.comments = psa.Evaluation_Comments__c;
        this.numberOfPayments = Integer.valueOf(psa.Number_of_Payments__c);
        this.totalBudget = psa.Activity_Budget__c;
        this.percentageVisibility = psa.Percentage_Visibility__c;
        this.limitToSelectedAccounts = psa.Limit_to_Selected_Accounts__c;
        this.isDirectRebate = psa.Activity_Type__c == null || psa.Activity_Type__c == 'Direct Rebate';
        this.accountWholesalerPreferred = psa.Account_Wholesaler_Preferred__c;
        this.accountWholesalerPreferredName = psa.Account_Wholesaler_Preferred_Name__c;
        this.accountWholesalerAlternate = psa.Account_Wholesaler_Alternate__c;
        this.accountWholesalerAlternateName = psa.Account_Wholesaler_Alternate_Name__c;
    }
}