force-app/main/default/objects/Contact/fields/Decision_Maker__c.field-meta.xml
<CustomField>
    <fullName>Decision_Maker__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Decision Maker</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Market__c/fields/Maximum_Agreement_Length__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Agreement_Length__c</fullName>
    <defaultValue>3</defaultValue>
    <label>Maximum Agreement Length</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Infowelders, NPA Rollout: Used to store the related Brand</description>
    <label>Brand</label>
    <referenceTo>Brand__c</referenceTo>
    <relationshipName>Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promotion__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Infowelders</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Promotions</relationshipLabel>
    <relationshipName>Promotions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Promotion__c/fields/Promotion_Activity__c.field-meta.xml
<CustomField>
    <fullName>Promotion_Activity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Infowelders</description>
    <label>Promotion Activity</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 OR 2) AND 3</booleanFilter>
        <filterItems>
            <field>Promotion_Activity__c.Market__r.Name</field>
            <operation>equals</operation>
            <valueField>$User.Market__c</valueField>
        </filterItems>
        <filterItems>
            <field>$User.Market__c</field>
            <operation>equals</operation>
            <value>ALL</value>
        </filterItems>
        <filterItems>
            <field>Promotion_Activity__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>Displaying only Active Promotion Activities in your Market</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Promotion_Activity__c</referenceTo>
    <relationshipLabel>Promotions</relationshipLabel>
    <relationshipName>Promotions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promotion__c/fields/Total_Listing_Fee__c.field-meta.xml
<CustomField>
    <fullName>Total_Listing_Fee__c</fullName>
    <label>Total Listing Fee</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Promotion_Activity__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Promotion_Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promotion_Activity__c/fields/Begin_Date__c.field-meta.xml
<CustomField>
    <fullName>Begin_Date__c</fullName>
    <description>INFOWELDERS</description>
    <label>Begin Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Promotion_Activity__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promotion_Activity__c/fields/Date_Approved__c.field-meta.xml
<CustomField>
    <fullName>Date_Approved__c</fullName>
    <label>Date Approved</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Promotion_Activity__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>INFOWELDERS</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Promotion_Activity__c/fields/Is_Length_in_Years__c.field-meta.xml
<CustomField>
    <fullName>Is_Length_in_Years__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Length in Years</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Promotion_Activity__c/fields/Length_of_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Length_of_Agreement__c</fullName>
    <description>Length of agreement in years</description>
    <label>Length of Agreement</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Promotion_Activity__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Infowelders</description>
    <label>Market</label>
    <referenceTo>Market__c</referenceTo>
    <relationshipName>Promotion_Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promotion_Activity__c/fields/Next_Email_Date__c.field-meta.xml
<CustomField>
    <fullName>Next_Email_Date__c</fullName>
    <label>Next Email Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Promotion_Activity__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Preliminary</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Concept</fullName>
            </value>
            <value>
                <fullName>Presented</fullName>
            </value>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Updated</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Committed</fullName>
            </value>
            <value>
                <fullName>Signed</fullName>
            </value>
            <value>
                <fullName>PO Created</fullName>
            </value>
            <value>
                <fullName>Contact Complete</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Promotion_Activity__c/fields/Total_Listing_Fee__c.field-meta.xml
<CustomField>
    <fullName>Total_Listing_Fee__c</fullName>
    <label>Total Listing Fee</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Promotion_Activity__c/fields/Wholesaler_Preferred__c.field-meta.xml
<CustomField>
    <fullName>Wholesaler_Preferred__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Wholesaler Preferred</label>
    <referenceTo>Wholesaler__c</referenceTo>
    <relationshipName>Activities_Wholesaler_Preferred</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promotion_Activity__c/fields/Wholesaler_Preferred_Name__c.field-meta.xml
<CustomField>
    <fullName>Wholesaler_Preferred_Name__c</fullName>
    <label>Wholesaler Preferred Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Promotion_Material_Item__c/fields/Activity__c.field-meta.xml
<CustomField>
    <fullName>Activity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Activity</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Activity is not active</errorMessage>
        <filterItems>
            <field>Promotion_Activity__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Promotion_Activity__c</referenceTo>
    <relationshipLabel>Promotion Material Items</relationshipLabel>
    <relationshipName>Promotion_Material_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promotion_Material_Item__c/fields/Brand_Status__c.field-meta.xml
<CustomField>
    <fullName>Brand_Status__c</fullName>
    <inlineHelpText>brand status placeholder</inlineHelpText>
    <label>Brand Status</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Must Stock</fullName>
            </value>
            <value>
                <fullName>May Stock</fullName>
            </value>
            <value>
                <fullName>Preferred Pouring</fullName>
            </value>
            <value>
                <fullName>Must Stock Pouring</fullName>
            </value>
            <value>
                <fullName>Preferred Premium</fullName>
            </value>
            <value>
                <fullName>By The Bottle</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Promotion_Material_Item__c/fields/Listing_Fee__c.field-meta.xml
<CustomField>
    <fullName>Listing_Fee__c</fullName>
    <label>Listing Fee</label>
    <precision>12</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Promotion_Material_Item__c/fields/Plan_Volume__c.field-meta.xml
<CustomField>
    <fullName>Plan_Volume__c</fullName>
    <label>Plan Volume</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Promotion_Material_Item__c/fields/Product_Custom__c.field-meta.xml
<CustomField>
    <fullName>Product_Custom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>NPA Rollout: Used to store the related Product. /* API name need to be changed to Product__c after Product remediation*/</description>
    <label>Product Name</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Promotion Material Items</relationshipLabel>
    <relationshipName>Promotion_Material_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promotion_Material_Item__c/fields/Promotion__c.field-meta.xml
<CustomField>
    <fullName>Promotion__c</fullName>
    <description>Infowelders: Used by CRM.
		NPA Rollout: Used to refer to Promotion.</description>
    <label>Promotion</label>
    <referenceTo>Promotion__c</referenceTo>
    <relationshipLabel>Promotion Material Items</relationshipLabel>
    <relationshipName>Promotion_Material_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Brazil_PSA_Contract_Controller_Test.cls
@isTest(SeeAllData=true)
public with sharing class Brazil_PSA_Contract_Controller_Test {
    static testMethod void unitTest1() {
        INFW_TestHelper helper = new INFW_TestHelper();

        Map<String, RecordTypeInfo> aRecordTypes = Schema.SObjectType.Account.getRecordTypeInfosByName();
        Map<String, RecordTypeInfo> cRecordTypes = Schema.SObjectType.Contact.getRecordTypeInfosByName();
        Map<String, RecordTypeInfo> pRecordTypes = Schema.SObjectType.Product__c.getRecordTypeInfosByName();
        Map<String, RecordTypeInfo> wRecordTypes = Schema.SObjectType.Wholesaler__c.getRecordTypeInfosByName();
        Map<String, RecordTypeInfo> paRecordTypes = Schema.SObjectType.Promotion_Activity__c.getRecordTypeInfosByName();
        Map<String, RecordTypeInfo> promoRecordTypes = Schema.SObjectType.Promotion__c.getRecordTypeInfosByName();
        Map<String, RecordTypeInfo> pmiRecordTypes = Schema.SObjectType.Promotion_Material_Item__c.getRecordTypeInfosByName();

        
        String rtWholesaler = wRecordTypes.get('Brazil').getRecordTypeId();
        String rtAccount = aRecordTypes.get('BRA - On Premise').getRecordTypeId();
        String rtParentAccount = aRecordTypes.get('Parent').getRecordTypeId();
        String rtContact = cRecordTypes.get('BRA - On Trade').getRecordTypeId();
        String rtWetGoods = pRecordTypes.get('Wet Goods').getRecordTypeId();
        String rtPSAActivity = paRecordTypes.get('BRA - PSA').getRecordTypeId();
        String rtPSAPromotion = promoRecordTypes.get('BRA - PSA').getRecordTypeId();
        String rtPSAPMI = pmiRecordTypes.get('BRA - PSA').getRecordTypeId();

        User manager = helper.createUser('System Administrator', 'Test', 'Manager', 'Brazil');
        insert manager;

        User user1 = helper.createUser('System Administrator','Test','User', 'Brazil');
        user1.ManagerId = manager.Id;
        insert user1;

        System.runAs(user1) {

            Market__c mBRA = helper.createMarket('Brazil');
            mBRA.Country_ISO_Code_2__c = 'BR';
            mBRA.Country_ISO_Code_3__c = 'BRA';
            mBRA.Maximum_Agreement_Length__c = 3;
            insert mBRA;

            Account parentAccount = helper.createAccount('Test BRA Parent Account', mBRA.Id, 'Wholesaler');
            parentAccount.RecordTypeId = rtParentAccount;
            parentAccount.Status__c = 'Active';
            parentAccount.Is_Active__c = true;
            parentAccount.ShippingStreet = '8 Otley Road';
            parentAccount.ShippingCity = 'Brazil';
            parentAccount.ShippingState = '';
            parentAccount.ShippingPostalCode = 'LS20 8AH';
            parentAccount.ShippingCountry = 'Brazil';
            insert parentAccount;

            Account childAccount = helper.createAccount('Test BRA Child Account', mBRA.Id, 'On Premise');
            childAccount.RecordTypeId = rtAccount;
            childAccount.ParentId = parentAccount.Id;
            childAccount.Is_Active__c = true;
            childAccount.Status__c = 'Active';
            childAccount.Sales_Route__c = 'WEST COAST';
            childAccount.ShippingStreet = '100 Acre Road';
            childAccount.ShippingCity = 'Brazil';
            childAccount.ShippingPostalCode = 'G20 OTL';
            childAccount.ShippingCountry = 'Brazil';
            insert childAccount;

            Contact contact1 = helper.createContact('Test BRA', 'Parent Contact', parentAccount.Id);
            contact1.Decision_Maker__c = true;
            contact1.RecordTypeId = rtContact;
            
            Contact contact2 = helper.createContact('Test BRA Child', 'Child Contact', childAccount.Id);
            contact2.Decision_Maker__c = true;
            contact2.RecordTypeId = rtContact;

            Contact[] l_Contacts = new Contact[]{contact1, contact2};
            insert l_Contacts;

            Wholesaler__c wholesaler1 = new Wholesaler__c(RecordTypeId=rtWholesaler,Name='WholesalerPreferred',Wholesaler_Name__c='Wholesaler1',Market__c=mBRA.Id,Is_Active__c=true);
            Wholesaler__c wholesaler2 = new Wholesaler__c(RecordTypeId=rtWholesaler,Name='WholesalerAlternate',Wholesaler_Name__c='Wholesaler2',Market__c=mBRA.Id,Is_Active__c=true);
            Wholesaler__c[] l_Wholesaler = new Wholesaler__c[]{wholesaler1, wholesaler2};
            insert l_Wholesaler;

            Brand__c brand = new Brand__c(Name='Brand');
            insert brand;
            
            List<Product__c> products = helper.createProducts(3, 'Wet Goods', mBRA.Id, brand.Id, false);
            insert products;
            
            Promotion_Activity__c psa1 = new Promotion_Activity__c();
            psa1.Name = 'Test PSA 1';
            psa1.RecordTypeId = rtPSAActivity;
            psa1.Begin_Date__c = Date.today();
            psa1.End_Date__c = psa1.Begin_Date__c.addDays(10);
            psa1.Account__c = parentAccount.Id;
            psa1.Contact__c = contact1.Id;
            psa1.Wholesaler_Preferred__c = wholesaler1.Id;
            psa1.Wholesaler_Preferred_Name__c = wholesaler1.Name;
            psa1.Is_Length_in_Years__c = false;
            psa1.Length_of_Agreement__c = 10;
            psa1.Reminder_Date__c = psa1.Begin_Date__c;
            psa1.Next_Email_Date__c = psa1.Begin_Date__c;
            psa1.Number_of_Payments__c = 4;
            psa1.Status__c = 'New';
            psa1.Total_Listing_Fee__c = 100000;
            psa1.Activity_Budget__c = 100000;
            psa1.Date_Approved__c = Date.today();
            
            Promotion_Activity__c[] l_PSA = new Promotion_Activity__c[]{psa1};
            insert l_PSA;

            Promotion__c promotion1 = new Promotion__c();
            promotion1.RecordTypeId = rtPSAPromotion;
            promotion1.Promotion_Activity__c = psa1.Id;
            promotion1.Account__c = parentAccount.Id;
            insert promotion1;

            Promotion_Material_Item__c psaItem1 = new Promotion_Material_Item__c();
            psaItem1.Activity__c = psa1.Id;
            psaItem1.Promotion__c = promotion1.Id;
            psaItem1.RecordTypeId = rtPSAPMI;
            psaItem1.Product_Custom__c = products[0].Id;
            psaItem1.Plan_Volume__c = 5;
            psaItem1.Brand_Status__c = 'Must Stock';
            psaItem1.Drink_Strategy__c = 'Perfect Serve';
            psaItem1.Listing_Fee__c = 100000;
            psaItem1.Promotional_Activity__c = 'Point of Sale';
            psaItem1.Training_and_Advocacy__c = 'Category Training';
            psaItem1.Outlet_to_Provide__c = 'Social Media Posting';
            insert psaItem1;

            Test.startTest();
                        
            ApexPages.StandardController stdController = new ApexPages.StandardController(psa1);
            PageReference docuSignPage = new PageReference('/apex/Brazil_PSA_ContractUK_PSA_Generate_DocuSign');
            docuSignPage.getParameters().put('id', psa1.Id);        
            Test.setCurrentPage(docuSignPage);
            
            Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
            req1.setComments('Submitting request');
            req1.setObjectId(psa1.Id);
            req1.setSubmitterId(user1.Id);
            req1.setProcessDefinitionNameOrId('Brazil_PSA');
            req1.setSkipEntryCriteria(true);
            Approval.ProcessResult result = Approval.process(req1);
            
            List<Id> newWorkItemIds = result.getNewWorkitemIds();
            System.debug('newWorkItemIds: ' + newWorkItemIds);
            Approval.ProcessWorkitemRequest workItem = new Approval.ProcessWorkitemRequest();
            workItem.setAction('Approve'); // manager approval
            workItem.setWorkitemId(newWorkItemIds.get(0));
            Approval.ProcessResult result2 = Approval.process(workItem);

            Brazil_PSA_Contract_Controller contractController = new Brazil_PSA_Contract_Controller();
            contractController.setThePSA(psa1);

            psa1.Number_of_Payments__c = 3;
            psa1.Date_Approved__c = psa1.Date_Approved__c.addMonths(1);
            update psa1;
            contractController.setThePSA(psa1);

            psa1.Number_of_Payments__c = 2;
            psa1.Date_Approved__c = psa1.Date_Approved__c.addMonths(1);
            update psa1;
            contractController.setThePSA(psa1);

            psa1.Number_of_Payments__c = 1;
            psa1.Date_Approved__c = psa1.Date_Approved__c.addMonths(1);
            update psa1;
            contractController.setThePSA(psa1);

            Test.stopTest();
        }
    }
}